import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, ExternalLink, ShieldCheck } from "lucide-react";
import { docPages, getDoc } from "@/lib/docs";

export function generateStaticParams() { return docPages.map((page) => ({ slug: page.slug })); }

const sections: Record<string, { title: string; intro: string; items: { title: string; body: string }[]; code?: string }> = {
  "getting-started": { title: "Getting started", intro: "Get a local Multi-Agent Studio environment running, then follow one workflow from definition to persisted result.", code: "pnpm install --frozen-lockfile\npnpm db:dev:up\npnpm db:migrate\npnpm dev", items: [{ title: "Prerequisites", body: "Node.js 20+, pnpm 10.17.0 and Docker for the local PostgreSQL services." }, { title: "The development loop", body: "The web app is the control plane. The TypeScript server validates, authorizes and executes workflows through LangGraph." }, { title: "Verify before you ship", body: "Run the full test suite, then build both the server and web packages to catch integration and type-level regressions." }] },
  architecture: { title: "Architecture", intro: "Multi-Agent Studio separates the browser control plane from the execution boundary that owns policy, compilation and runtime state.", items: [{ title: "Control plane", body: "Next.js owns the authenticated product experience. Its server-side BFF forwards an authenticated principal assertion to the execution server." }, { title: "Execution server", body: "Hono authenticates, authorizes and validates the request before compiling WorkflowDefinition into a LangGraph StateGraph." }, { title: "Runtime and persistence", body: "AgentRuntime, ToolRuntime, Memory and RunStore are explicit boundaries. PostgreSQL stores durable entities, events, approvals and long-term memory." }] },
  security: { title: "Security model", intro: "Security is designed around explicit trust boundaries and fail-closed defaults rather than implicit client behavior.", items: [{ title: "The browser is not authoritative", body: "Workflow, agent, tool, credential and principal values from the browser are treated as untrusted input. Server-side ownership and policy checks decide what can run." }, { title: "Workers have an explicit boundary", body: "Local workers are for trusted code. Container workers use a restricted image, non-root user, read-only filesystem, dropped capabilities and disabled networking by default." }, { title: "Secrets do not enter domain records", body: "Provider credentials are resolved just in time and are not stored in agent records, workflow definitions, events, logs or worker specifications." }] },
  memory: { title: "Memory", intro: "Memory is split by purpose: short-term run state for execution continuity and long-term memory for durable, tenant-aware recall.", items: [{ title: "Short-term state", body: "Checkpoints and paused context belong to the run and support approval recovery and restart-aware execution." }, { title: "Long-term memory", body: "MemoryService applies namespace and tenant authorization before retrieval. PostgreSQL and pgvector provide the durable store." }, { title: "Evidence matters", body: "Retrieval should remain traceable to stored memories and source metadata; the explorer exists to make that evidence visible." }] },
  "tools-and-approvals": { title: "Tools & approvals", intro: "Tools are registered capabilities, not arbitrary workflow instructions. Human approval is a first-class execution state.", items: [{ title: "Tool registry", body: "Agents and workflow nodes refer to server-owned tool IDs. Function and configured HTTP tools are supported; sensitive capabilities remain allowlisted." }, { title: "Approval lifecycle", body: "LangGraph interrupt/resume carries bounded proposals through approved or rejected branches without repeating the provider call." }, { title: "Run evidence", body: "Run events, snapshots and approval records make the execution timeline inspectable and recoverable." }] },
  credentials: { title: "Credential Broker", intro: "Production credentials are issued as short-lived, single-use leases bounded to tenant, principal, run and provider context.", items: [{ title: "Issue and consume", body: "The execution server requests a lease from the broker, consumes it atomically and never exposes the underlying secret to the browser or workflow data." }, { title: "Policy and audit", body: "The broker enforces membership, provider, alias, quota and budget policy. Audit records use a hash chain and append-only storage controls." }, { title: "Deployment boundary", body: "The standalone broker defaults to deny-all until deployment supplies its authorization and quota sources. Real certificates and Vault connectivity remain deployment proof points." }] },
  development: { title: "Development guide", intro: "Keep local setup deterministic and use the verification commands as part of the development workflow.", code: "pnpm test --runInBand\npnpm --filter server build\npnpm --filter web build\ngit diff --check", items: [{ title: "Environment", body: "Runtime configuration belongs close to the service that consumes it. Do not commit secrets or treat local fake providers as production proof." }, { title: "Database", body: "Migrations are explicit and run outside application startup. PostgreSQL is used for Studio, memory and broker persistence." }, { title: "Focused verification", body: "Separate unit, browser, provider, persistence and restart evidence. A passing focused suite does not prove every production boundary." }] },
  limitations: { title: "Limitations & roadmap", intro: "The project documents what is proven, what is deployment-specific and what is intentionally deferred.", items: [{ title: "Known deployment gaps", body: "Process-local rate limiting needs a shared store for multi-instance broker deployments. Standalone authorization directory wiring is deployment-specific." }, { title: "Proof boundaries", body: "mTLS is code-verified but real certificates are not exercised here. The Vault adapter is proven against a fake HTTP store, not a production Vault deployment." }, { title: "Next direction", body: "Continue hardening observability, durable recovery, production sinks and worker-direct credential consumption while keeping the fail-closed posture." }] },
};

export default async function DocPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const page = getDoc(slug);
  const content = sections[slug];
  if (!page || !content) return <div className="empty-state"><h1>Page not found</h1><Link href="/">Return home</Link></div>;
  const currentIndex = docPages.findIndex((item) => item.slug === slug);
  const previous = docPages[currentIndex - 1];
  const next = docPages[currentIndex + 1];
  return <article className="doc-page"><div className="breadcrumbs"><Link href="/">Docs</Link><span>/</span><span>{page.group}</span><span>/</span><strong>{page.title}</strong></div><header className="doc-header"><span className="eyebrow">{page.group.toUpperCase()}</span><h1>{content.title}</h1><p>{content.intro}</p><div className="source-line"><CheckCircle2 size={15} /> Current source: <code>{page.source}</code><a href={`https://github.com/Itshossein128/multi-agent/blob/main/${page.source}`}><ExternalLink size={13} /> source</a></div></header>{slug === "architecture" && <ArchitectureDiagram />}{content.code && <pre className="code-block"><code>{content.code}</code></pre>}<div className="prose-grid">{content.items.map((item) => <section key={item.title}><h2>{item.title}</h2><p>{item.body}</p></section>)}</div>{slug === "security" && <div className="callout"><ShieldCheck size={20} /><div><strong>Security principle</strong><p>Every boundary should have one clear owner, an explicit authorization decision and a safe failure mode.</p></div></div>}<footer className="doc-footer">{previous ? <Link href={`/docs/${previous.slug}`}><ArrowLeft size={15} /><span><small>Previous</small>{previous.title}</span></Link> : <span />}{next ? <Link href={`/docs/${next.slug}`} className="next"><span><small>Next</small>{next.title}</span><ArrowRight size={15} /></Link> : <span />}</footer></article>;
}

function ArchitectureDiagram() { return <div className="architecture-diagram"><div className="diagram-row"><div className="diagram-node browser"><span>01</span><strong>Browser / Next.js</strong><small>Control plane</small></div><div className="diagram-line" /><div className="diagram-node server"><span>02</span><strong>Hono execution server</strong><small>Auth · policy · compile</small></div><div className="diagram-line" /><div className="diagram-node runtime"><span>03</span><strong>LangGraph runtime</strong><small>Agents · tools · memory</small></div></div><div className="diagram-branch"><div>PostgreSQL<br /><small>durable state</small></div><div>Credential Broker<br /><small>short-lived leases</small></div><div>Container worker<br /><small>isolated execution</small></div></div></div>; }
